Repository ehdgnsl01/Tools_Algorithm_Study, pull requests merged in 2024-05, with the labels that each got.

#29 2 김성휘
  김성휘/B_1085.java
Labels: 리뷰 기다리는중🔥, 김성휘

#30 240501 이태호 백준 1439
  이태호/11399.py
  이태호/1439.py
Labels: 리뷰 기다리는중🔥, 이태호

#31 2024-05-01 B_1247
  김성휘/B_1247_부호
Labels: 리뷰 기다리는중🔥, 김성휘

#32 240501 boj 2910
  조영효/2910. 빈도 정렬/README.md
  조영효/2910. 빈도 정렬/빈도 정렬.cc
Labels: 리뷰 기다리는중🔥, 조영효

#33 240501 백준 10818
  김동훈/단계별/4.1차원 배열/10818.cpp
Labels: 리뷰 기다리는중🔥, 김동훈

#34 24.5.1 / 1157번 / 단어 연습
  성민서/단계별로 풀어보기/심화 1/단어 공부/word_study.cpp
Labels: 리뷰 기다리는중🔥, 성민서

#35 2024-05-02
  김성휘/B_2752_세수정렬
Labels: 리뷰 기다리는중🔥, 김성휘

#36 2024-05-02 10798
  .idea/misc.xml
  .idea/workspace.xml
  고희재/.idea/workspace.xml
  고희재/10798/VerticalReading.java
Labels: 리뷰 기다리는중🔥, 고희재

#41 Create 1920.java
  홍찬영/단계별로 풀어보기/1920.java
Labels: 리뷰 기다리는중🔥, 홍찬영

#47 240508 백준 10811
  김동훈/단계별/4.1차원 배열/10811.cpp
Labels: 리뷰 기다리는중🔥, 김동훈

#49 240508 boj 2852
  조영효/2852. NBA 농구/NBA 농구.cc
  조영효/2852. NBA 농구/README.md
Labels: 리뷰 기다리는중🔥, 조영효

#50 Create 11047.py
  이태호/11047.py
Labels: 리뷰 기다리는중🔥, 이태호

#61 24-05-12 백준 1475
  이태호/1158.py
  이태호/1475.py
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 이태호

#55 240511 백준 1158
  이태호/1158.py
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 이태호

#60 Create 2630.java
  홍찬영/단계별로 풀어보기/2630.java
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 홍찬영

#59 240512 boj 1436
  조영효/1436. 영화감독 숌/README.md
  조영효/1436. 영화감독 숌/영화감독 숌.cc
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 조영효

#58 Create 1037.java
  홍찬영/단계별로 풀어보기/1037.java
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 홍찬영

#57 2024-05-12
  김성휘/B_4673_셀프 넘버
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 김성휘

#56 2024-05-11
  김성휘/B_1065_한수
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 김성휘

#54 240510 백준 2161
  이태호/2108.py
  이태호/2161.py
  이태호/test.py
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 이태호

#53 2024-05-10 백준1152
  고희재/1152/NumOfWords.java
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 고희재

#51 240509 백준 10809
  김동훈/.vscode/settings.json
  김동훈/단계별/5. 문자열/10809.cpp
Labels: 리뷰 기다리는중🔥, 저번주꺼✔️, 김동훈

#62 24.05.13 / 성민서 / 2444번 / 별 찍기 - 7
  성민서/단계별로 풀어보기/심화 1/별 찍기 - 7.cpp
Labels: 리뷰 기다리는중🔥, 리뷰긴박✔️

#65 2024-05-14 22607
  .idea/workspace.xml
  고희재/22607/YourAverage.java
Labels: 리뷰 기다리는중🔥, 리뷰긴박✔️, 고희재

#66 24-05-14 백준 7568
  이태호/2108.py
  이태호/7568.py
Labels: 리뷰 기다리는중🔥, 리뷰긴박✔️, 이태호

#69 24-05-15 백준 2669
  이태호/2669.py
Labels: 리뷰 기다리는중🔥, 리뷰긴박✔️, 이태호

#70 240516 백준 1152
  김동훈/단계별/5. 문자열/1152.cpp
Labels: 리뷰 기다리는중🔥, 리뷰긴박✔️, 김동훈

#84 2024-05-26
  김성휘/B_10988_팰린드롬인지 확인하기
  김성휘/B_14425_문자열집합
Labels: 리뷰 기다리는중🔥, 김성휘

#82 24-05-22 백준 11382
  이태호/11382.py
Labels: 리뷰 기다리는중🔥, 리뷰긴박✔️, 이태호

#81 24-05-22 백준 10926
  이태호/10926.py
Labels: 리뷰 기다리는중🔥, 리뷰긴박✔️, 이태호

#79 240520 백준 1316
  김동훈/단계별/6. 심화 1/1316.cpp
Labels: 리뷰 기다리는중🔥, 리뷰긴박✔️, 김동훈
